### ISSUE TITLE
ERROR: Tag latest not found in repository docker.io/clever/godoc-docker

### ISSUE THREAD

**Issue by edrex** [Clever/godoc-docker#6]
I made a `docker-compose.yml`:

```
version: '2'
services:
  godoc:
    image: clever/godoc-docker
    ports:
    - "80:8080"
    links:
    - redis
    environment:
      REDIS_URL: redis:6379
  redis:
    image: redis:alpine
```
```
> docker-compose up
⋮
ERROR: Tag latest not found in repository docker.io/clever/godoc-docker
```

`image: clever/godoc-docker:b5f1b24` works.

Something weird with the way you're pushing images to the repository?
